### PR TITLE
Feature/sign up

### PR DESCRIPTION
**Pull request by Bryan-Cee**
**What does this PR do?**
Creates a sign up page

**Description of Task to be completed?**

1. Create a sign up page for creating accounts.
2. Style the page with CSS.

**How should this be manually tested?**

- Clone the repo to your local machine:
- `git clone https://github.com/Bryan-Cee/Fast-Food-Fast.git`
- Navigate into the project
- `cd /Fast-Food-Fast/UI/pages/user`
- Open _signup.html_ with your browser

**What are the relevant pivotal tracker stories?**
[#160088585](https://www.pivotaltracker.com/story/show/160088585)

**Screenshot**
signup

### CODE REVIEW

**Comment by danielotieno** [comment]
Awesome

**Comment by ThaDeveloper** [comment]
Nice one

**Comment by PromasterGuru** [comment]
Awesome:)

**Comment by iddle254** [comment]
this got me feeling hungry

**Comment by iddle254** [comment]
how did you do the logo tho?

**Comment by bettblake08** [comment]
That's a neat design. My suggestion would be to make the "Welcome" text left aligned. It may look better.

**Pull request closed without merging**
