### PR TITLE
Feature/landing page

### PR DESCRIPTION
**Pull request by Bryan-Cee**
**What does this PR do?**
Creates a login page

**Description of Task to be completed?**

- Create a landing page for logging in.
- Style the page with CSS.

**How should this be manually tested?**

- Clone the repo to your local machine:
- `git clone https://github.com/Bryan-Cee/Fast-Food-Fast.git`
- Navigate into the project
-` cd /Fast-Food-Fast/UI/pages/user`
- Open index.html with your browser

What are the relevant pivotal tracker stories?
[#160088421](https://www.pivotaltracker.com/story/show/160088421)

**Screenshot**
fast-food-fastfinal

### CODE REVIEW

**Comment by SilasKenneth** [comment]
Nice and simple

**Comment by Gabkings** [comment]
Awesome

**Comment by Georgeygigz** [comment]
Nice One

**Comment by ThaDeveloper** [comment]
great UI

**Pull request closed without merging**
